interface Card {
  name: string;
  src: string;
}

const deckCards: Card[] = [
  {
    name: "apple",
    src: "./ressources/apple.svg",
  },
  {
    name: "banana",
    src: "./ressources/banana.svg",
  },
  {
    name: "brocoli",
    src: "./ressources/brocoli.svg",
  },
  {
    name: "cherry",
    src: "./ressources/cherry.svg",
  },
  {
    name: "pepper",
    src: "./ressources/pepper.svg",
  },
  {
    name: "straw",
    src: "./ressources/straw.svg",
  },
];

export default deckCards;
